### ISSUE TITLE
Import many-to-many relations not working.

### ISSUE THREAD

**Issue by Timonwatteny** [pimcore/data-importer#80] opened 2021-08-05 07:47 UTC
**Expected behavior**
Import an array of dataobjects on a many-to-many field via the data-importer creates the relation for every element provided.

Transformation result is of type dataObjectArray and there is no option to iterate over the array so I expect the load dataobject to do this.
![Screenshot 2021-08-04 at 11 52 48](https://user-images.githubusercontent.com/31765954/128312200-50e1e263-8de7-4381-bb0f-3813b571b77b.png)

**Actual behavior**
Nothing happens, no relations are added to the dataobject.

Values with only one dataobject are accepted:
![Screenshot 2021-08-04 at 12 00 15](https://user-images.githubusercontent.com/31765954/128312217-4b225dc6-9d27-4e39-a62d-275c74165937.png)

**Steps to reproduce**
Create a class with a many-to-many relation to another class
Create a data objects importer configuration in data hub.
Explode a value on a delimiter (; in this case) to have an array of dataobjects in the transformation pipeline
Load dataobject in the next step of the transformation pipeline (type = dataObjectArray)
In the data target add the many-to-many field.
Run the import.

**Comment by Timonwatteny** [comment] 2021-08-05 09:09
I'v noticed that this only works on ID. Exploding on "," and loading on ID does the trick. 

Is it known that attribute and path are not yet supported?

**Comment by fashxp** [comment] 2021-08-17 10:11
hmm, works fine for me with `path` too. 

the preview of transformation result looks correct?

**Comment by HeicoSindel** [comment] 2021-09-08 18:58
Maybe not the right place for my question, but as the import for advanced M2M Relations are not possible with the data-importer, is it possible to write the data directly into the DB - in the table object_relations_(id)? Because i have to store almost 2000 relations on the advanced relations and i have to do it with an ETL-Job... but i dont know, if the one table is enough or there are some other dependencies

**Comment by fashxp** [comment] 2021-09-28 14:42
we are working on support for advanced many to many relations, a first draft you can find here https://github.com/pimcore/data-importer/pull/96. 

please don't update db directly, you most likely will forget something and end up in a corrupt db.

**Comment by fashxp** [comment] 2021-09-28 14:43
I'll close this issue now as it is not reproducible. please feel free to reopen with more details.

**Closed as completed by fashxp** 2021-09-28 14:43 UTC

**Comment by lucas-langa** [comment] 2023-03-08 15:28
I think the problem is the space before the delimiter, I also had this issue with a comma separated delimiter that had a space before the value not accepting most of my input because it had no space before the comma, try to remove the space before the semi colon delimiter, although this may not be relevant to you anymore
