### ISSUE TITLE
[Bug]: Uncaught TypeError probably causes configuration editing not possible 

### ISSUE THREAD

**Issue by LR-stackoverflow** [pimcore/data-importer#350] opened 2023-08-22 10:07 UTC
### Expected behavior

I have installed the data importer. I have created a new data objects importer configuration in the pimcore admin backend. 
But if I click on it, the configuration does not open. 

### Actual behavior

Instead of opening the configuration for editing, an error occurs in the broswers developer console. 

```
configItemDataObject.js?_dc=1:305 Uncaught TypeError: pimcore.plugin.pimcoreDataImporterBundle.configuration.components.logTab is not a constructor
    at klass.buildLoggerTab (configItemDataObject.js?_dc=1:305:27)
    at klass.getPanels (configItemDataObject.js?_dc=1:25:18)
    at klass.initialize (configItemDataObject.js?_dc=1:67:27)
    at new klass (class.js?_dc=b4be185b1207aaf74e976513adb97f8c94138510:33:29)
    at klass.createConfigPanel (dataImporterDataObject.js?_dc=1:18:26)
    at klass.<anonymous> (dataImporterDataObject.js?_dc=1:35:22)
    at Object.callback (ext-all-debug.js?_dc=b4be185b1207aaf74e976513adb97f8c94138510:10872:39)
    at constructor.onComplete (ext-all-debug.js?_dc=b4be185b1207aaf74e976513adb97f8c94138510:32800:21)
    at constructor.onStateChange (ext-all-debug.js?_dc=b4be185b1207aaf74e976513adb97f8c94138510:32750:16)
    at ext-all-debug.js?_dc=b4be185b1207aaf74e976513adb97f8c94138510:32737:20
```

### Steps to reproduce

1. install Pimcore in the newest version (11.0.7)
2. install the data hub in the newest version (1.6.3)
3. install admin-ui-classic-bundle in the newest version (1.0.5)
4. install the data importer in the newest version (1.8.2)
5. open the datahub in the pimcore admin backend
6. Add Configuration -> Data Objects Importer
7. give the new configuration a name e.g. test
8. click on the new configuration to edit it
9. open the browsers developer console (Chrome) in the console tab

**Comment by dvesh3** [comment] 2023-08-25 08:28
@LR-stackoverflow could you please check https://github.com/pimcore/data-importer/issues/344#issuecomment-1647935687 and close it since it is a duplicate of #344

**Closed as completed** 2023-08-31 12:21 UTC
Labels: Bug
