### ISSUE TITLE
[Improvement]: SQLSTATE[08004] [1040] Too many connections issue on pimcore when running datahub importer 

### ISSUE THREAD

**Issue by bhagawatpal** [pimcore/data-importer#355] opened 2023-09-08 13:22 UTC
### Improvement description

 Too many connections issue on pimcore 10.6 version when running datahub importer 
 is there use  \Pimcore::collectGarbage();?

**Comment by dvesh3** [comment] 2023-09-12 08:10
duplicate of #354

**Closed as completed by dvesh3** 2023-09-12 08:10 UTC
Labels: Improvement
