### ISSUE TITLE
[Improvement]: Add option to enable and disable Import logs info messages

### ISSUE THREAD

**Issue by bhagawatpal** [pimcore/data-importer#349] opened 2023-08-19 17:11 UTC
### Feature description

Datahub Importer - there should be an option in datahub importer  to  enable and disable Import logs info message because if there are millions of data imports applications logs create  inodes so that server is down due to inodes occupies 100% on Linux server.

**Comment by dvesh3** [comment] 2023-08-21 09:51
duplicate of #79

**Closed as completed by dvesh3** 2023-08-21 09:51 UTC
Labels: Improvement, Task

**Comment by bhagawatpal** [comment] 2023-08-21 10:58
bin/console datahub:data-importer:process-queue-parallel --no-logs
In this way you can disable all logs but I need to disable only info logs

**Comment by dvesh3** [comment] 2023-08-21 11:12
`bin/console datahub:data-importer:process-queue-parallel --no-logs` disables info logs only. please see https://github.com/pimcore/data-importer/pull/258/files
