### ISSUE TITLE
[Bug]: Folders not created when importing CSV via Datahub/Objects Data Importer

### ISSUE THREAD

**Issue by bernagozzi** [pimcore/data-importer#156] opened 2022-01-24 13:46 UTC
### Expected behavior

Short: When importing a CSV via Objects Data Importer with a column with the Path each object should have in Pimcore, Pimcore should automatically create the required folders as it happened with the CSV Import functionality in Pimcore 6.x.

Verbose:
We have updated the Pimcore installation of one of our customer from 6.x to Pimcore X. Since they were making intensive use of CSV Import, we are trying to replace the old CSV Import functionality with a Data Objects Importer via DataHub.
The old CSV import in Pimcore 6.x automatically created all the required folders that were specified in the path, but this doesn’t seem to happen with the Data Objects Importer in Pimcore X. We have also found this: https://github.com/pimcore/data-importer/issues/73

The possibility to have the Data Objects Importer create folders while importing CSVs and creating/moving Objects would basically cover a functionality that was already there in Pimcore 6.x, so I believe that adding a “Find or create Parent” location strategy for Element Creation and Element Location Update would be great. Since this was the core functionality of the CSV Import in Pimcore 6, maybe even just updating the “Find Parent” location strategy (instead of creating a new one) would be ok.

Can you please provide a feedback on this? Thanks a lot in advance, keep up the good work!

### Actual behavior

If the paths have folders which don’t exist in Pimcore, the folders are not created and the objects are created in the fallback path.

### Steps to reproduce

- Have a csv file of objects to import/create in Pimcore with a column which specifies the path the objects must have in Pimcore.
- Datahub: create an Object Data Importer
- Data Source section: import the csv file and set CSV as file format.
- Import Settings/Resolver/Element Creation and/or Import Settings/Resolver/Element Location Update:
    - Location Strategy: Find Parent
    - Find Strategy: Path
    - Data Source Index: Select the csv column with the path
    - Fallback Path: any path
- Import Settings/Mappings: map all the columns with the relevant attributes
- Save
- Execution: Start

**Comment by fashxp** [comment] 2022-02-02 19:51
duplicate of https://github.com/pimcore/data-importer/issues/73

`FindParent` is not restricted for folders, could also load any other data object (to create hierarchies). Thus we should go for an additional location strategy `FindOrCreateFolder`

**Closed as completed by fashxp** 2022-02-02 19:51 UTC
Labels: Bug
