### ISSUE TITLE
Resolver element loading strategy (attribute and path) not working

### ISSUE THREAD

**Issue by bitfactory-justin-kouwenhoven** [pimcore/data-importer#68] opened 2021-07-22 13:46 UTC
### Attribute

When use the resolver element loading strategy attribute option, any existing data objects won't get updates.
Instead a new data object will be created.

<img width="876" alt="Schermafbeelding 2021-07-22 om 15 39 51" src="https://user-images.githubusercontent.com/15174824/126648569-b12865ba-9009-4879-acd8-f39e9c70e103.png">

### Path

When use the resolver element loading strategy path option and using the mapping to use a column value as the system key, existing objects won't be updated. Instead it's trying to create a new object with the same path (with column value as key). The import creates an error log for each entry.

<img width="1035" alt="Schermafbeelding 2021-07-22 om 15 45 14" src="https://user-images.githubusercontent.com/15174824/126649408-c48e5308-bc96-4e8a-8fb2-8b0f1f0c7c1e.png">

Also trying to open the log file object results in a error page:
<img width="1052" alt="Schermafbeelding 2021-07-22 om 15 46 12" src="https://user-images.githubusercontent.com/15174824/126649538-34206ef5-b6a9-4cfa-8f00-e6e0f4b4164d.png">

**Comment by fashxp** [comment] 2021-07-22 14:14
cannot reproduce. 
are your elements published? please also see https://github.com/pimcore/data-importer/issues/24

**Comment by bitfactory-justin-kouwenhoven** [comment] 2021-07-22 14:45
@fashxp 
I removed all my data objects, then i changed the element publish option to always publish and started the import several times.
This worked in combination with element loading attribute, the data objects are updated.

It did not work if i changed the element loading to path. The same error from above is still triggered.

**Comment by fashxp** [comment] 2021-07-22 14:48
can you please further debug. all loading should happen here: https://github.com/pimcore/data-importer/blob/1.1/src/Resolver/Load/PathStrategy.php#L34

**Comment by fashxp** [comment] 2021-08-03 19:11
@bitfactory-justin-kouwenhoven  any updates?

**Comment by fashxp** [comment] 2021-08-17 10:52
@bitfactory-justin-kouwenhoven ping

**Comment by skoch-twocream** [comment] 2021-09-07 13:28
> @fashxp via Mail
> [...] Ich würde es aber wie im Issue geschrieben nicht mit einer Checkbox lösen, sondern eine eigene Location Strategy erstellen – sollte eigentlich sehr einfach möglich sein.  [...]

Please assigne me to this issue ;-)

**Comment by fashxp** [comment] 2021-09-08 17:45
@skochTC  didn't you mean this one: https://github.com/pimcore/data-importer/issues/73?

**Comment by skoch-twocream** [comment] 2021-09-08 19:25
> @skochTC didn't you mean this one: #73?

Oh... okay there are two todos for me :-D For this issue, I can reproduce it when the attribute of the resolver is the first column (index 0) in the XLS.

Is there a deadline for the next bundle release?

**Comment by fashxp** [comment] 2021-09-08 20:23
we established a bi-weekly release cycle for bug fix releases ... next release would be on September 15th, if any bugfixes are available.

**Comment by skoch-twocream** [comment] 2021-09-13 08:02
Sorry, but I don't think I'll be able to do that at work until the 15th. Privately I have this week also no time.

I scheduled this for me for the next week.

**Comment by fashxp** [comment] 2021-09-14 07:53
@skochTC  fyi see #90   .... a different topic, sorry..

**Comment by skoch-twocream** [comment] 2021-09-21 10:25
After testing for a while with the new version, I can no longer reproduce this.

@bitfactory-justin-kouwenhoven - Can you try this again please?

**Comment by skoch-twocream** [comment] 2021-09-22 09:32
@fashxp - Okay! Sorry I actually can reproduce it...

This is my selection of valid XLS header columns:
![image](https://user-images.githubusercontent.com/54348050/134318903-91f716ed-cf55-4fa9-b7dd-478e48622e91.png)

The ExtJs-Store looks like this:
![image](https://user-images.githubusercontent.com/54348050/134317251-fd88432e-e49b-4950-ac75-c8dcb4fba515.png)

I added a new listener to the select field to dump the current value:

https://github.com/pimcore/data-importer/blob/1.x/src/Resources/public/js/pimcore/configuration/components/resolver/load/attribute.js#L100

```js
                        listeners: {
                            select: function(context) {
                                console.log(context.value);
                                console.log(context);
                                console.log(this.configItemRootContainer.columnHeaderStore);
                            }.bind(this)
                        }
```

This allowed me to find this out:
![image](https://user-images.githubusercontent.com/54348050/134317934-7c570eae-56e8-4102-83cc-6b0ca76aa54f.png)

The "valueField" defined in the Ext component does not work with the DataIndex "0":
```js
                {
                        xtype: 'combo',
                        fieldLabel: t('plugin_pimcore_datahub_data_importer_configpanel_data_source_index'),
                        name: this.dataNamePrefix + 'dataSourceIndex',
                        value: this.data.dataSourceIndex,
                        store: this.configItemRootContainer.columnHeaderStore,
                        displayField: 'label',
                        valueField: 'dataIndex', // This field...
                        forceSelection: false,
                        queryMode: 'local',
                        triggerOnClick: false
                },
```

You can also see this in the save request:
![image](https://user-images.githubusercontent.com/54348050/134318244-a87ebe98-95c7-4142-8559-c632777aee34.png)

I am not that familiar with Ext.JS. Do you have any idea why this is?

**Comment by skoch-twocream** [comment] 2021-09-24 09:16
After a few more test runs I could now find out that the problem is not with the index "0" but on the label. The question still remains, why the Ext.JS-Store stores the label as value and not the "dataIndex"?

In the XLS, the attribute looks like this:
![image](https://user-images.githubusercontent.com/54348050/134650468-08a49d13-ba26-4e17-9120-61da69eb9dab.png)

As you can see, there is a line break in the column.

**Comment by fashxp** [comment] 2021-09-29 09:57
hmm, tried to reproduce this on my end ... also added the console logs ... 

![image](https://user-images.githubusercontent.com/8792145/135247009-98e23446-be2e-4004-b23c-3554c79e681c.png)

for me it works just fine.

**Comment by skoch-twocream** [comment] 2021-09-29 10:28
Hmm I really have no idea... Attached is the XLS I used.

[Preview_E-Com_MT_20210713_mit_Identifier(1).xlsx](https://github.com/pimcore/data-importer/files/7251059/Preview_E-Com_MT_20210713_mit_Identifier.1.xlsx)

Can you try that again with this? Otherwise it may be browser dependent?

I use Firefox as my default browser (93.0b9 (64-bit))

**Comment by mcop1** [comment] 2021-10-04 12:50
Hello, 

I am sorry, but I can´t reproduce this issue on my end of the side, even if I use the provided XLSX file. Neither with Chrome nor with Firefox.

**Comment by stg231178** [comment] 2021-10-07 07:20
> After a few more test runs I could now find out that the problem is not with the index "0" but on the label. The question still remains, why the Ext.JS-Store stores the label as value and not the "dataIndex"?
> 
> In the XLS, the attribute looks like this: ![image](https://user-images.githubusercontent.com/54348050/134650468-08a49d13-ba26-4e17-9120-61da69eb9dab.png)
> 
> As you can see, there is a line break in the column.

I tested this with an own excel file and i think its really a problem with skipping the first row. For every excel sheet i tried, the first row (labels) made it impossible to import the data below. Maybe someone should have a look at the skipping logic

**Comment by fashxp** [comment] 2021-10-07 07:30
as already noted ... we cannot reproduce this on our end. we highly appreciate any PR to fix that.

**Comment by skoch-twocream** [comment] 2021-10-07 07:42
@stg231178 - Which Pimcore version are you using?

I expect that this is an ExtJS issue. Which is possibly fixed in Pimcore 10?

https://github.com/pimcore/pimcore/pull/7824

Anyway, we solved the problem under Pimcore version 6 by removing the line break.
This topic is hard to reproduce and debug.

**Comment by fashxp** [comment] 2021-10-07 07:52
ahh of course ... that would make sense, since Pimcore 10 switched to ExtJs 7. 
We just tried Pimcore 10.

**Comment by stg231178** [comment] 2021-10-07 07:58
> @stg231178 - Which Pimcore version are you using?
> 
> I expect that this is an ExtJS issue. Which is possibly fixed in Pimcore 10?
> 
> [pimcore/pimcore#7824](https://github.com/pimcore/pimcore/pull/7824)
> 
> Anyway, we solved the problem under Pimcore version 6 by removing the line break. This topic is hard to reproduce and debug.

Pimcore 10.0.8
Data-Importer 1.2.1

**Comment by fashxp** [comment] 2021-10-07 09:26
hmm ... ok, could you then please debug a bit further? or is it reproducible on our public demo too?

**Comment by stg231178** [comment] 2021-10-07 09:31
> hmm ... ok, could you then please debug a bit further? or is it reproducible on our public demo too?

at the moment i have the effect that it work with "skip first row" but i cant reproduce the failure anymore. But i will test it with new import configurations

**Comment by fashxp** [comment] 2021-10-27 12:32
I'll close that for now. Feel free to create folluwup tickets when you have more insights. thank you very much!

**Closed as completed by fashxp** 2021-10-27 12:32 UTC
