### ISSUE TITLE
[Bug]: Pass an empty value to the As Numeric operator shows wrong preview

### ISSUE THREAD

**Issue by robertSt7** [pimcore/data-importer#359] opened 2023-09-19 09:02 UTC
### Expected behavior

Preview show 0

### Actual behavior

Preview shows empty

### Steps to reproduce

Pass an empty value to the As Numeric operator

**Comment by kingjia90** [comment] 2023-09-22 13:10
I wouldn't consider this as a bug, `As Numeric` was intended to work the same way as `floatval` and it is properly documented see:
https://github.com/pimcore/data-importer/blob/764dda04a5bfec189f5638b74d941cb4cd1cdcf5/doc/03_Configuration/06_Mapping_Configuration/02_Transformation_Pipeline.md?plain=1#L38C56-L38C64

https://github.com/pimcore/data-importer/blob/764dda04a5bfec189f5638b74d941cb4cd1cdcf5/src/Mapping/Operator/Factory/Numeric.php#L28-L37

Knowing that `is_numeric('')` or `is_numeric(null)` that would be `false`, we wouldn't be returning something "numeric" if it wasn't `0`.

Should we introduce a new operator instead that can return `null` when empty?

**Comment by dvesh3** [comment] 2023-09-26 09:27
Fixed by #363

**Closed as completed by dvesh3** 2023-09-26 09:27 UTC
Labels: Bug
