### ISSUE TITLE
Importer Not Working .Nothing Happens When Click On Start For Manual Execution

### ISSUE THREAD

**Issue by kumar2112** [pimcore/data-importer#41] opened 2021-06-04 11:34 UTC
Hi All
I am using datahub importer version 1 for one of the my project. .I have configured it but folllowing issues i am facing
1.On click of start it does nothing just shows the below screen..
![image](https://user-images.githubusercontent.com/12470739/120794700-30b59d00-c556-11eb-998c-8d42d9cd0376.png)
We have to use the console command to execute the import process
2. We could not find the way how we can manage the relational fields
3. We can not restrict the classes according to role wise permissions.
![image](https://user-images.githubusercontent.com/12470739/120795010-8e49e980-c556-11eb-9818-ace2372b01d4.png)

**Comment by al3wb** [comment] 2021-06-04 19:10
Greetings! I had exactly the same problem with importing data - when I click on "Start", the process does not go and the progress bar does not move, no errors are generated. Maybe someone can record a short video of the complete process of importing data from a CSV and XML file?
![image](https://user-images.githubusercontent.com/13482518/120851539-9f5c2000-c581-11eb-8c09-612ba8c6f417.png)

**Comment by MarcoGuiducci** [comment] 2021-06-05 15:18
Same Issue for me on version 1.1

**Comment by fashxp** [comment] 2021-06-05 18:39
Ad import: import is always executed asynchronously, make sure you have configured the cronjobs: see also https://pimcore.com/docs/data-importer/current/Installation.html#page_Bundle-Configuration

And also https://pimcore.com/docs/data-importer/current/Import_Execution_Details.html ...

**Comment by fashxp** [comment] 2021-06-07 08:27
Ad 2 - Relational fields: You can use operators in the transformation pipeline to assign to relational fields, like `Load DataObjects` or `Load Assets`. See [here](https://pimcore.com/docs/data-importer/current/Configuration/Mapping_Configuration/Transformation_Pipeline.html#page_List-of-available-Operators) and also the sample import configuration in our [demo](https://demo.pimcore.com/admin):

![image](https://user-images.githubusercontent.com/8792145/120984471-f842d880-c77a-11eb-950e-029a40598dfc.png)

**Comment by fashxp** [comment] 2021-06-07 08:28
Ad 3 - Restricting classes: Not yet possible. PRs are welcome :) .

**Comment by Makskknd** [comment] 2021-06-21 11:53
Good day! Faced the same problem when trying to upload categories and products. When the "start" button is pressed, the progress bar does not move. According to the answers in the topic, it is not clear how to fix the situation. If it's not difficult - please write down a short video for help (with a demonstration of the necessary correct actions).

**Comment by fashxp** [comment] 2021-06-21 12:38
please add following cron-jobs to your system: 

```
# Process import queue items that can be executed in parallel
* * * * * php /home/project/www/bin/console datahub:data-importer:process-queue-parallel --processes=2

# Process import queue items that need to be executed sequentially 
* * * * * php /home/project/www/bin/console datahub:data-importer:process-queue-sequential 
```

**Comment by Makskknd** [comment] 2021-06-21 14:53
Thank you, but we already had this, we can't understand this error in the cron logs yet "Jun 21 14: 46: 01 pimcore CRON[28014]: (root) CMD (php /var/www/html/pimcore/bin/console datahub:data-importer:process-queue-sequential # Edit this file to introduce tasks to be run by cron.)"
![1](https://user-images.githubusercontent.com/43819391/122782642-8f4e7b00-d2b9-11eb-9196-e861fdc40fdc.jpg)

**Comment by Makskknd** [comment] 2021-06-21 16:10
I followed your recommendations, but unfortunately it didn’t help. The data is still not being filled in. The progress bar stands still and does not move.
![Скриншот 21-06-2021 191026](https://user-images.githubusercontent.com/43819391/122793857-536ce300-d2c4-11eb-86a8-6db6f6c79431.jpg)

**Comment by fashxp** [comment] 2021-06-21 16:11
What happens when you execute these commands manually?

**Comment by Makskknd** [comment] 2021-06-21 16:18
When you run a script, you give out such a message
![Скриншот 21-06-2021 191531](https://user-images.githubusercontent.com/43819391/122794926-73e96d00-d2c5-11eb-922f-e1d5ec955ad5.jpg)

**Comment by Makskknd** [comment] 2021-06-21 16:55
![Скриншот 24-05-2021 173802](https://user-images.githubusercontent.com/43819391/122799663-ac3f7a00-d2ca-11eb-8c87-ce96cab685c6.jpg)

**Comment by Makskknd** [comment] 2021-06-21 16:56
![2](https://user-images.githubusercontent.com/43819391/122799728-bceff000-d2ca-11eb-85b4-68da7072a7b4.jpg)

**Comment by fashxp** [comment] 2021-06-22 07:10
hmm, then the queue is empty and nothing is there to import. 

the import process consists of two steps: 
1) preparation: data source is read and queue items for import are created. 
2) processing: processing of the queue and actual importing of the data. 

step 1) this is executed when the import button is pressed. 
step 2) is executed by the commands I mentioned above (depending on import type there is sequential and parallel processing). 

For details please also have a look [in the docs](https://pimcore.com/docs/data-importer/current/Import_Execution_Details.html). 

your case (progress bar stands still, but execution of commands does not process any items) only should happen, if some error happened. steps to debug:
- Have a look at the `bundle_data_hub_data_importer_queue` table - is it empty, or are there some entries? 
- If there are entries, retry executing the processing jobs. Depending on the `jobType` column value, `datahub:data-importer:process-queue-parallel` or `datahub:data-importer:process-queue-sequential` is responsible for executing. 
- Are there any log entries in application logger or Pimcore log files? 

Please share your findings ...

**Comment by Makskknd** [comment] 2021-06-23 07:54
Good afternoon, can I clarify if I'm doing the right thing, at the moment I want to load categories from xml

Example of a string from xml to be loaded:
   category id="90401">Category_NAME/category>
   category id="198118" parentId="90401">Category_NAME1/category>
   category id="198119" parentId="90401">Category_NAME2/category>

![Скриншот 23-06-2021 104726](https://user-images.githubusercontent.com/43819391/123057320-71dff500-d410-11eb-9f7d-6c8151c1685c.png)

The XML itself is loaded the first field (id) is of the type "number", the second field (value) is "Static text", I wanted to clarify how to add the third field (parentId)


![Скриншот 23-06-2021 105321](https://user-images.githubusercontent.com/43819391/123058211-4578a880-d411-11eb-89ad-6db856778e7c.png)

![Скриншот 23-06-2021 103924](https://user-images.githubusercontent.com/43819391/123058273-51fd0100-d411-11eb-92b6-64093f21aedb.png)

maybe I indicated something wrong ?

**Comment by fashxp** [comment] 2021-06-23 08:15
this is sightly off topic now ... can you move this post to https://github.com/pimcore/pimcore/discussions/ please?

**Comment by Makskknd** [comment] 2021-06-24 07:49
The issue is resolved, when using root@pimcore:/var/www/html/pimcore/bin# php console datahub:data-importer:process-queue-sequential
, the import went

**Comment by Makskknd** [comment] 2021-06-24 07:50
The issue is resolved, when using root@pimcore:/var/www/html/pimcore/bin# php console datahub:data-importer:process-queue-sequential
, the import went

**Comment by wcchew76** [comment] 2021-07-11 08:45
> The issue is resolved, when using root@pimcore:/var/www/html/pimcore/bin# php console datahub:data-importer:process-queue-sequential
> , the import went

Beware when you do that. On my Dockerized install version, when I ran manually using Root account, I have to run the following command to change owner back to user where Pimcore web server is configured. Otherwise "Version" history for records created by data-importer Process operation (under Root user) will not be accessible by Pimcore web server process.
`chown -R www-data:www-data var`

**Closed as completed** 2021-10-27 12:33 UTC

**Comment by chaitu2140** [comment] 2022-09-06 21:14
> please add following cron-jobs to your system:
> 
> ```
> # Process import queue items that can be executed in parallel
> * * * * * php /home/project/www/bin/console datahub:data-importer:process-queue-parallel --processes=2
> 
> # Process import queue items that need to be executed sequentially 
> * * * * * php /home/project/www/bin/console datahub:data-importer:process-queue-sequential 
> ```

**I need help as the importer bar is not progressing further.**

**Comment by chaitu2140** [comment] 2022-09-06 21:18
Need help in Import Functionality as the progress bar is not moving. I can see the data in the bundle_data_hub_data_importer_queue table. I definitely feel I am doing wrong in the Crontab execution process. But I am new to Crontab execution process and even to PHP. Request to help/guide me as it is important for our PoC.
